### ISSUE TITLE
Can't import module files

### ISSUE THREAD

**Issue by kesmit13** [bellard/quickjs#162]
I have quickjs compiled to wasm and running it from the wasmtime runtime. I'm running into an issue with import modules though. I attached a virtual file system to access the files and if I do a `std.loadFile` of a particular file, it reads it just fine.

This works:
```
str = "print(std.loadFile('./lib/msgpack.js'));\n";
val2 = JS_Eval(ctx, str, strlen(str), "<input>", JS_EVAL_TYPE_MODULE);
```

However, if I try to `import` that same file, I get an error saying that it could not load the module.
```
str = "import { serialize, deserialize } from './lib/msgpack.js';\n";
val2 = JS_Eval(ctx, str, strlen(str), "<input>", JS_EVAL_TYPE_MODULE);
```

The code above gives this message:
```
ReferenceError: could not load module 'lib/msgpack.js'
```

The module I'm loading is this one, although I did change the `window` references to `globalThis`: https://github.com/ygoe/msgpack.js/blob/master/msgpack.js. I'm guessing there's something incompatible with the
way exports are done, but I don't know what the fix is.

**Comment by aaronhuggins** [comment]
It's not an EcmaScript Module. It's compatible with Node.JS CommonJS modules and browser Window/Global object. When you eval the script string, it works because you aren't trying to treat it as a module, you're executing arbitrary JavaScript instead.

You would need to refactor the script to be compatible with ES2020 modules.
