### ISSUE TITLE
Why js_class_id_alloc is global?

### ISSUE THREAD

**Issue by ryhor-spivak** [bellard/quickjs#214]
Is there a reason why js_class_id_alloc (https://github.com/bellard/quickjs/blob/master/quickjs.c#L1283) is a global variable and not a part of JSRuntime? 

This variable only increments in JS_NewClassID and never resets. 

This creates problems for browser-like usage of quickjs: application browses some pieces of content (pages) and creates new JSRuntime for each new page and frees runtimes of closed pages. Each newly created JSRuntime need to work with bigger and bigger class_ids, because it shares global js_class_id_alloc with all other runtimes. This requires bigger and bigger size of JSRuntime.class_array and eventually reach maximum 1<<16 value (https://github.com/bellard/quickjs/blob/master/quickjs.c#L3415) after which everything stops working.

We solve this problem by making js_class_id_alloc a member of JSRuntime in our fork of the library. Are there any downsides to this approach?

**Comment by saghul** [comment]
That's also how we solved it: https://github.com/quickjs-ng/quickjs/commit/5ce2957e2384998a762f3f22b1e32bf1c0d1749c

**Comment by bellard** [comment]
The idea is that the class IDs are global and identical for all the runtimes which eases data passing between runtimes e.g. with workers. That's why JS_NewClassID() returns a new ID only if the existing one is zero. So there is no class ID leak provided JS_NewClassID() is correctly used.

Of course it could still be possible to add a runtime local class ID allocation as in quickjs-ng, but it is not really needed with the current design.
