### ISSUE TITLE
Class method with name `get` throws incorrect "invalid property name" exception

### ISSUE THREAD

**Issue by richarddavison** [bellard/quickjs#261]
When using arrow functions to define methods on a class, QJS throws exception:
```
SyntaxError: invalid property name
    at ./test.js:2:6

```
```javascript
class TestClass {
  get = () => console.log("get");
}

new TestClass().get();
```

**Comment by gabrielmfern** [comment]
I think this might be a bigger issue here, we can't have any property — be it on a class or an object — that has a name for a reserved keyword. This doesn't seem to be the behavior of other engines, though, since Node and the browsers I've tested with don't really care.

https://github.com/bellard/quickjs/blob/3b45d155c77bbdfe9177b1e03db830d2aff0b2a8/quickjs.c#L22385-L22400

I think it should probably not check for reserved keywords like this, since the spec doesn't really mention anything on this.

**Comment by chqrlie** [comment]
I just tried this:
```
class TestClass { "get" = () => console.log("get"); }
```
And it works.  I am not sure it is ECMA conformant...

**Comment by gabrielmfern** [comment]
@chqrlie Are you also considering allowing a class method to have a name of a reserved keyword? I'm facing a compatibility issue that happens because:

```javascript
class Example {
  static() { return 1234 }
}
```

is not supported on quickjs

**Comment by chqrlie** [comment]
@gabrielmfern: yes, the fix should also allow this particular case.
