### ISSUE TITLE
Alternative Makefile to demonstrate just how small QuickJS is?

### ISSUE THREAD

**Issue by IngwiePhoenix** [bellard/quickjs#43]
I am getting more and more into [vlang](https://github.com/vlang) and I am thinking of writing a direct wrapper for QuickJS. But I would love to keep this as small as possible but also provide the full feature set.

So my question is:
- What files do I *actually* need to compile on Linux, Windows and macOS?
- Is it save to concatenate all the C files into a single one - or should I keep everything as a separate entity?

The latter one is especially important as I am working with other single-file (amalgamated) libraries such as mongoose, in which it is actually save to include the C file, because it in turn includes the header file.

In V, it is possible to define what headers to include in a wrapper - so I would probably just include the entirity of QuickJS alongside the wrapper to expose just a single module, so the user doesn't have to mess with finding the right source/header files. Is this a safe practice with this library?

Thanks!

**Comment by bellard** [comment]
The Makefile of QuickJS lists all the necessary object files (see QJS_LIB_OBJS). Since there are few files it is quite easy to find all the related C files. Some headers must be kept as separate files because they are included several times. The rest could be in a single file but it has a limited interest.
